name: Native-AMD64

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      #Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: dashaun
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: sdkman
#        uses: sdkman/sdkman-action@main
#        id: sdkman
#        with:
#          candidate: java
#          version: 22.3.1.r17-grl
      - uses: actions/setup-java@v2
        with:
          distribution: 'liberica' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          submodules: true
      #Build Image
      - name: Build Image
        run: ./mvnw -Pnative spring-boot:build-image -DskipTests
      #Tag the version    
      #Deploy the image to the Docker registry
      - name: Push Images to Docker Registry
        run: docker push -a dashaun/dev.dashaun.function.redis.geospatial


  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: dashaun
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: pull-arm64
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          retry_wait_seconds: 60
          max_attempts: 6
          command: docker pull dashaun/dev.dashaun.function.redis.geospatial:$GITHUB_REF_NAME-aarch_64
      - name: create-manifest
        run: |
          docker manifest create dashaun/dev.dashaun.function.redis.geospatial:$GITHUB_REF_NAME --amend dashaun/dev.dashaun.function.redis.geospatial:$GITHUB_REF_NAME-x86_64 --amend dashaun/dev.dashaun.function.redis.geospatial:$GITHUB_REF_NAME-aarch_64
          docker manifest push dashaun/dev.dashaun.function.redis.geospatial:$GITHUB_REF_NAME
          docker manifest create dashaun/dev.dashaun.function.redis.geospatial:latest --amend dashaun/dev.dashaun.function.redis.geospatial:$GITHUB_REF_NAME-x86_64 --amend dashaun/dev.dashaun.function.redis.geospatial:$GITHUB_REF_NAME-aarch_64
          docker manifest push dashaun/dev.dashaun.function.redis.geospatial:latest